apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-deploy
  namespace: {{ $.Values.namespace }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - name: techtrends
        image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        ports:
          - containerPort: {{ $.Values.service.containerPort }}
        {{- if index $.Values.resources "techtrends" }}
        resources:
          {{- toYaml (get $.Values.resources "techtrends") | nindent 12 -}}
        {{- end }}
        livenessProbe:
          httpGet:
            path: {{ $.Values.probes.livenessProbe.path }}
            port: {{ $.Values.service.targetPort }}
          initialDelaySeconds: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: {{ $.Values.probes.readinessProbe.path }}
            port: {{ $.Values.service.targetPort }}
          initialDelaySeconds: 3
          periodSeconds: 10
