apiVersion: v1
description: A Helm chart for deploying Frappe/ERPNext based applications on a Kubernetes cluster
name: techtrends
keywords: 
  - techtrends
version: 1.0.0
maintainers:
  - name: shreyasDaripadhar