namespace: sandbox
service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP
  containerPort: 3111
image:
  repository: techtrends
  tag: latest
  pullPolicy: IfNotPresent
replicaCount: 1
resources:
  techtrends:
    requests:
      memory: 64Mi
      cpu: 250m
    limits:
      memory: 128Mi
      cpu: 500m
probes:
  livenessProbe:
    path: /healthz
  readinessProbe:
    path: /healthz